fix: the text displayed on HSS is wrong when it is not signout period
ieeeuoft/makeuoft-2023 pull request #26
Opened 2023-02-08 07:11 UTC by Leo6Leo

Also, update the styling for the page showing the team code

## Steps to QA

- Change the hardware signout period to a future date, and visit the http://localhost:3000/acknowledgement page. Please make sure you made an application, accept yourself, and set your review a decision send date. 
- Change the hardware signout period to a past date, fill in the acknowledgment form, and see the new designed team code generation page.

2023-02-08 07:12 UTC, Leo6Leo reviewed
@lukecheseldine  Luke try to review this ticket as well!

2023-02-08 07:12 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/constants.js
> +export const hardwareSignOutStartDate = new Date(2023, 1, 10, 12, 0); // Be careful! The Feburary is 1
@lukecheseldine The date here is really tricky, the month starts from 0 actually.

2023-02-08 07:22 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/pages/Acknowledgement/Acknowledgement.test.tsx
> +                    `🎉${mockUserWithoutProfile.first_name}, you're ready to get started. <br /> We've placed you in Team <strong>${createProfileAPIResponse.data.team}</strong> <br /> but you can leav
@YuYing-Liang  Yuying any suggestions on how to fix this?

2023-02-08 20:01 UTC, YuYing-Liang commented on hackathon_site/dashboard/frontend/src/pages/Acknowledgement/Acknowledgement.test.tsx
> +                    `🎉${mockUserWithoutProfile.first_name}, you're ready to get started. <br /> We've placed you in Team <strong>${createProfileAPIResponse.data.team}</strong> <br /> but you can leav
remove the emoji and the html tags and try using a regex string e.g. 
```
new RegExp(`${mockUserWithoutProfile.first_name}, you're ready to get started. We've placed you in Team ${createProfileAPIResponse.data.team} but you can leave and join another team anytime.`, 'i')
```

2023-02-08 21:35 UTC, Leo6Leo commented on hackathon_site/dashboard/frontend/src/pages/Acknowledgement/Acknowledgement.test.tsx
> +                    `🎉${mockUserWithoutProfile.first_name}, you're ready to get started. <br /> We've placed you in Team <strong>${createProfileAPIResponse.data.team}</strong> <br /> but you can leav
Yeah the original one is the regex string, but it looks less nicer. I cannot add `<br />` in it.

2023-02-09 20:41 UTC, Mustaballer requested changes

2023-02-09 20:41 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/pages/Acknowledgement/Acknowledgement.test.tsx
> +            //     getByText(
remove the commented code if its unnecessary

2023-02-09 20:41 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/pages/Acknowledgement/Acknowledgement.tsx
> +        console.log(hardwareSignOutStartDate);
remove log statement and extra space that was added

2023-02-09 20:41 UTC, Mustaballer commented on hackathon_site/dashboard/frontend/src/constants.js
> +export const hardwareSignOutStartDate = new Date(2023, 1, 10, 12, 0); // Be careful! The Feburary is 1
remove the comment at the end

2023-02-09 21:43 UTC, merged