added qr scanner code
ieeeuoft/makeuoft-2023 pull request #36
Opened 2023-02-16 19:51 UTC by YuYing-Liang

## Overview

- adds qr code scanning to makeuoft.ca
- scanner only appears when admins login

## Unit Tests Created

- none for now

## Steps to QA

- run migrations, collectstatic and compile scss
- as a participant, take a photo of ur qrcode when you login
- login as an admin, go to qr scanner page and scan ur participant code with camera
- might need to change times in settings/__init__.py
- check for errors:
- throws an error for duplicate sign-ins
- participant who hasn't RSVP'd and isn't accepted or a user that doesn't exist
- sign in data should appear on django admin site (model called UserActivity)
- test for general user experience and fluidity

2023-02-16 22:36 UTC, Mustaballer requested changes
One suggestion to change 'User activitys' to 'User activities' in Django Admin Site.

When I sign in multiple times(works first time), I get the following error. Is that what we expect?
![image](https://user-images.githubusercontent.com/43456930/219494704-a9945056-7acc-4037-9518-3a1ececd842f.png)

When I try to sign in an email that doesn't exist it lets me know. When I input an email that does exist, and didn't apply, it lets me know with correct message.  If I don't rsvp, I don't get access to the QR code as a participant. ✔

2023-02-16 22:36 UTC, Mustaballer commented on hackathon_site/event/static/event/styles/scss/_variables.scss
> +    error: #b00020,
Remove duplicate keys for error and success. Plus run prettier to pass template checks

2023-02-16 22:36 UTC, Mustaballer commented on hackathon_site/hackathon_site/settings/__init__.py
> +        "time": datetime(2023, 1, 13, 17, 0, 0, tzinfo=TZ_INFO),  # Oct 10th @ 11am
We should adjust the times of the events to match the participant package

2023-02-17 06:16 UTC, Mustaballer reviewed
It works wonderfully! I tested signing in multiple times, and it was able to track that and gave me the correct error. When changing events, there were no issues with signing in again. Before your merge the PR, you should run prettier to pass the template checks, and on a final note to update the last two event times to match the participant package :)

2023-02-17 06:21 UTC, Mustaballer commented on hackathon_site/event/jinja2/event/admin_qr_scanner.html
> +            console.log(oldData.split(';'))
Remove log statement

2023-02-17 14:11 UTC, Mustaballer approved these changes
Great job!

2023-02-17 15:40 UTC, Leo6Leo requested changes
Temporary Merging Blocking

2023-02-18 13:25 UTC, merged